#
# Docker file for Recipe site development server
#
# Build with
#
#   docker build --build-arg UID=$UID -t <name>:<tag> -f <dockerfile> .
#
# For example if building a local version, you could do:
#
#   docker build --build-arg UID=$UID -t local/recipe_site:dev -f Dockerfile_dev .
#
# To run an interactive shell inside this container, do:
#
#   docker run -ti --entrypoint /bin/bash local/recipe_site:dev
#


FROM fnndsc/ubuntu-python3:latest
MAINTAINER jbernal0019 "jbernal0019@yahoo.es"

ENV VERSION="0.1"

# Pass a UID on build command line (see above) to set internal UID
ARG UID=1001
ENV UID=$UID

ENV APPROOT="/home/localuser/recipe_backend" REQPATH="/usr/src/requirements"
COPY ["./requirements", "${REQPATH}"]
COPY ["./docker-entrypoint.sh", "/usr/src"]

RUN apt-get update \
  && apt-get install -y libpq-dev                            \
  && pip3 install -r ${REQPATH}/local.txt                           \
  && useradd -u $UID -ms /bin/bash localuser

# Start as user localuser
USER localuser

WORKDIR $APPROOT
ENTRYPOINT ["/usr/src/docker-entrypoint.sh"]
EXPOSE 8080

#CMD ["manage.py", "runserver", "0.0.0.0:8010"]
