#
# Docker file for Recipe site development server
#
# Build with
#
#   docker build -t <name>:<tag> -f <dockerfile> .
#
# For example if building a local version, you could do:
#
#   docker build -t local/recipe_site:dev -f Dockerfile_dev .
#
# To run an interactive shell inside this container, do:
#
#   docker run -ti --entrypoint /bin/bash local/recipe_site:dev
#


FROM fnndsc/ubuntu-python3:latest
MAINTAINER jbernal0019 "jbernal0019@yahoo.es"

ENV APPROOT="/usr/src/recipe_backend" REQPATH="/usr/src/requirements" VERSION="0.1"
COPY ["./requirements", "${REQPATH}"]
COPY ["./docker-entrypoint.sh", "/usr/src"]

# Pass a UID on build command line (see above) to set internal UID
ARG UID=1001
ENV UID=$UID

RUN apt-get update \
  && apt-get install sudo                                             \
  && useradd -u $UID -ms /bin/bash localuser                          \
  && addgroup localuser sudo                                          \
  && echo "localuser:localuser" | chpasswd                            \
  && adduser localuser sudo                                           \
  && apt-get install -y libmysqlclient-dev                            \
  && pip3 install -r ${REQPATH}/local.txt                             \
  && mkdir /usr/users                                                 \
  && chmod 777 /usr/users                                             \
  && echo "localuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR $APPROOT
ENTRYPOINT ["/usr/src/docker-entrypoint.sh"]
EXPOSE 8080

# Start as user $UID
# For now this is disabled so the service runs as root to 
# easily write to the managed db volume.
# USER $UID
