# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3'

services:
  recipe_site_dev:
    image: jbernal0019/recipe_site:dev
    volumes:
      - ./recipe_backend:/home/localuser/recipe_backend
    ports:
      - "8080:8080"
    depends_on:
      - recipe_site_dev_db
    labels:
      name: "Recipe_site"
      role: "Development server"

  recipe_site_dev_db:
    image: postgres:11
    volumes:
      - recipe_site_dev_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipe_site_dev
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=Recipe1234
    labels:
      name: "Recipe_site PostgreSQL Database"
      role: "Development database"

volumes:
  recipe_site_dev_db_data:
